AllCops:
  Exclude:
    - 'utils/aws_helper.rb'

Metrics/LineLength:
  Max: 120

Style/RaiseArgs:
  EnforcedStyle: compact

Style/BracesAroundHashParameters:
  EnforcedStyle: context_dependent
  
Style/IndentHash:
  EnforcedStyle: consistent
  
Style/BracesAroundHashParameters:
  EnforcedStyle: braces

Metrics/MethodLength:
  Max: 80
  
Metrics/ClassLength:
  Max: 150

Style/ClassVars:
  Exclude:
    - 'tests/utils/keyvalparser_test.rb'

Metrics/AbcSize:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false
  
Metrics/CyclomaticComplexity:
  Enabled: false
