AllCops:
  Exclude:
    - 'utils/aws_helper.rb'
    - 'chef-repo/cookbooks/**/*'
    
Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Max: 150

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 80

Metrics/PerceivedComplexity:
  Enabled: false

Style/BracesAroundHashParameters:
  EnforcedStyle: braces

Style/ClassVars:
  Exclude:
    - 'tests/utils/keyvalparser_test.rb'
    - 'tests/utils/aws_helper_test.rb'

Style/IndentHash:
  EnforcedStyle: consistent

Style/RaiseArgs:
  EnforcedStyle: compact
